Update restore-database.yaml

diff --git a/.github/workflows/restore-database.yaml b/.github/workflows/restore-database.yaml
--- a/.github/workflows/restore-database.yaml
+++ b/.github/workflows/restore-database.yaml
@@ -41,3 +41,22 @@ jobs:
       if: github.event.inputs.version == 'Restore'
       run: |
         echo "Hello"
+        aws s3 cp s3://cognianextgen-rds-backup/data.sql .
+        PGPASSWORD=Agb09hbs2 pg_dump -h cognianxtgen.cluster-cpdaobpdl4ur.us-east-2.rds.amazonaws.com -U cognianxtgenuser -d cognianxtgendb -f backup.sql
+        # Check if the dump command was successful (exit status 0)
+        if [ $? -eq 0 ]; then
+            echo "Dump command executed successfully"
+            
+            # Perform the restore command
+            PGPASSWORD=Agb09hbs2 pg_restore -h cognianxtgen.cluster-cpdaobpdl4ur.us-east-2.rds.amazonaws.com -U cognianxtgenuser -d cognianxtgendb data.sql
+            
+            # Check if the restore command was successful (exit status 0)
+            if [ $? -eq 0 ]; then
+                echo "Restore command executed successfully"
+                aws s3 cp backup.sql s3://cognianextgen-rds-backup/backup/
+            else
+                echo "Restore command failed"
+            fi
+        else
+            echo "Dump command failed"
+        fi
